package com.avintangu.taxiapp.resources;

import android.content.Context;

public class Jsonresource {

    private static Context jContext;

    public Jsonresource(Context context) {
        jContext = context;

    }

    /* Return Json string */
    public String retJson() {
        String sourcestr = "{"
                + "	\"trips\": [{"
                + "		\"id\": 608,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-08-16 10:49:25\","
                + "		\"pickup_lat\": -1.32349230,"
                + "		\"pickup_lng\": 36.84356380,"
                + "		\"pickup_location\": \"St James, Nairobi\","
                + "		\"dropoff_lat\": -1.32341300,"
                + "		\"dropoff_lng\": 36.84341990,"
                + "		\"dropoff_location\": \"Nextgen Mall, Nairobi\","
                + "		\"pickup_date\": \"2019-08-16 10:50:32\","
                + "		\"dropoff_date\": \"2019-08-16 11:26:32\","
                + "		\"type\": \"Lady\","
                + "		\"driver_id\": 13,"
                + "		\"driver_name\": \"Alize\","
                + "		\"driver_rating\": 5,"
                + "		\"driver_pic\": \"https://demotaxiapp/p13.jpg\","
                + "		\"car_make\": \"Honda\","
                + "		\"car_model\": \"Civic\","
                + "		\"car_number\": \"KCR-100P\","
                + "		\"car_year\": 2012,"
                + "		\"car_pic\": \"https://demotaxiapp/c13.jpg\","
                + "		\"duration\": 36,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 1.54,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 253,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 585,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-08-09 06:45:05\","
                + "		\"pickup_lat\": -1.29526860,"
                + "		\"pickup_lng\": 36.88664890,"
                + "		\"pickup_location\": \"Manyanja, Nairobi\","
                + "		\"dropoff_lat\": -1.32347630,"
                + "		\"dropoff_lng\": 36.84335600,"
                + "		\"dropoff_location\": \"St James, Nairobi\","
                + "		\"pickup_date\": \"2019-08-09 06:45:38\","
                + "		\"dropoff_date\": \"2019-08-09 08:34:38\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 109,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 15.51,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 894,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 542,"
                + "		\"status\": \"CANCELED\","
                + "		\"request_date\": \"2019-08-07 16:35:06\","
                + "		\"pickup_lat\": -1.32593000,"
                + "		\"pickup_lng\": 36.84029830,"
                + "		\"pickup_location\": \"Bandari, Nairobi\","
                + "		\"dropoff_lat\": -1.32213750,"
                + "		\"dropoff_lng\": 36.82889830,"
                + "		\"dropoff_location\": \"New Apostolic Church, Nairobi\","
                + "		\"pickup_date\": \"2019-08-07 16:35:39\","
                + "		\"dropoff_date\": null,"
                + "		\"type\": \"HavaXL\","
                + "		\"driver_id\": 11,"
                + "		\"driver_name\": \"George\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p11.jpg\","
                + "		\"car_make\": \"Toyota\","
                + "		\"car_model\": \"Rav4\","
                + "		\"car_number\": \"KBG-871X\","
                + "		\"car_year\": 2009,"
                + "		\"car_pic\": \"https://demotaxiapp/c11.jpg\","
                + "		\"duration\": 0,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 0,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 0,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 541,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-08-07 16:15:06\","
                + "		\"pickup_lat\": -1.32306500,"
                + "		\"pickup_lng\": 36.84333830,"
                + "		\"pickup_location\": \"St James, Nairobi\","
                + "		\"dropoff_lat\": -1.32763000,"
                + "		\"dropoff_lng\": 36.83899830,"
                + "		\"dropoff_location\": \"Amboseli Estate, Nairobi\","
                + "		\"pickup_date\": \"2019-08-07 16:17:46\","
                + "		\"dropoff_date\": \"2019-08-07 16:18:46\","
                + "		\"type\": \"HavaXL\","
                + "		\"driver_id\": 11,"
                + "		\"driver_name\": \"George\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p11.jpg\","
                + "		\"car_make\": \"Toyota\","
                + "		\"car_model\": \"Rav4\","
                + "		\"car_number\": \"KBG-871X\","
                + "		\"car_year\": 2009,"
                + "		\"car_pic\": \"https://demotaxiapp/c11.jpg\","
                + "		\"duration\": 1,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 2.11,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 200,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 523,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-08-07 11:29:04\","
                + "		\"pickup_lat\": -1.29649240,"
                + "		\"pickup_lng\": 36.82344140,"
                + "		\"pickup_location\": \"Makaburini, Nairobi\","
                + "		\"dropoff_lat\": -1.32349580,"
                + "		\"dropoff_lng\": 36.84341830,"
                + "		\"dropoff_location\": \"St James, Nairobi\","
                + "		\"pickup_date\": \"2019-08-07 11:30:05\","
                + "		\"dropoff_date\": \"2019-08-07 11:46:05\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 16,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 9.19,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 440,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 511,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-08-06 22:03:23\","
                + "		\"pickup_lat\": -1.26831380,"
                + "		\"pickup_lng\": 36.90579310,"
                + "		\"pickup_location\": \"Phase 4/Car Wash, Nairobi\","
                + "		\"dropoff_lat\": -1.26476400,"
                + "		\"dropoff_lng\": 36.91168510,"
                + "		\"dropoff_location\": \"Unnamed Road, Nairobi\","
                + "		\"pickup_date\": \"2019-08-06 22:03:37\","
                + "		\"dropoff_date\": \"2019-08-06 22:14:37\","
                + "		\"type\": \"Lady\","
                + "		\"driver_id\": 13,"
                + "		\"driver_name\": \"Alize\","
                + "		\"driver_rating\": 5,"
                + "		\"driver_pic\": \"https://demotaxiapp/p13.jpg\","
                + "		\"car_make\": \"Honda\","
                + "		\"car_model\": \"Civic\","
                + "		\"car_number\": \"KCR-100P\","
                + "		\"car_year\": 2012,"
                + "		\"car_pic\": \"https://demotaxiapp/c13.jpg\","
                + "		\"duration\": 11,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 1.35,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 200,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 464,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-08-06 06:27:33\","
                + "		\"pickup_lat\": -1.29090000,"
                + "		\"pickup_lng\": 36.89254990,"
                + "		\"pickup_location\": \"Manyanja Rd, Nairobi\","
                + "		\"dropoff_lat\": -1.28629870,"
                + "		\"dropoff_lng\": 36.82660160,"
                + "		\"dropoff_location\": \"Magomano, Tom Mboya St, Nairobi\","
                + "		\"pickup_date\": \"2019-08-06 06:27:55\","
                + "		\"dropoff_date\": \"2019-08-06 07:06:55\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 39,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 18.33,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 806,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 446,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-08-05 08:04:35\","
                + "		\"pickup_lat\": -1.29927810,"
                + "		\"pickup_lng\": 36.82408000,"
                + "		\"pickup_location\": \"Makaburini, Nairobi\","
                + "		\"dropoff_lat\": -1.32332100,"
                + "		\"dropoff_lng\": 36.84364140,"
                + "		\"dropoff_location\": \"St James, Nairobi\","
                + "		\"pickup_date\": \"2019-08-05 08:04:52\","
                + "		\"dropoff_date\": \"2019-08-05 08:26:52\","
                + "		\"type\": \"Lady\","
                + "		\"driver_id\": 13,"
                + "		\"driver_name\": \"Alize\","
                + "		\"driver_rating\": 5,"
                + "		\"driver_pic\": \"https://demotaxiapp/p13.jpg\","
                + "		\"car_make\": \"Honda\","
                + "		\"car_model\": \"Civic\","
                + "		\"car_number\": \"KCR-100P\","
                + "		\"car_year\": 2012,"
                + "		\"car_pic\": \"https://demotaxiapp/c13.jpg\","
                + "		\"duration\": 22,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 4.24,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 316,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 444,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-08-05 06:19:11\","
                + "		\"pickup_lat\": -1.27330780,"
                + "		\"pickup_lng\": 36.89655960,"
                + "		\"pickup_location\": \"Mama Lucy Hospital, Nairobi\","
                + "		\"dropoff_lat\": -1.28403340,"
                + "		\"dropoff_lng\": 36.82602310,"
                + "		\"dropoff_location\": \"Timboroa Ln, Nairobi\","
                + "		\"pickup_date\": \"2019-08-05 06:20:26\","
                + "		\"dropoff_date\": \"2019-08-05 07:03:26\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 43,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 13.23,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 669,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 417,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-08-01 07:22:40\","
                + "		\"pickup_lat\": -1.28408020,"
                + "		\"pickup_lng\": 36.82604940,"
                + "		\"pickup_location\": \"Accra Road, Tuskys Imara, Nairobi\","
                + "		\"dropoff_lat\": -1.32332670,"
                + "		\"dropoff_lng\": 36.84337040,"
                + "		\"dropoff_location\": \"St James, Nairobi\","
                + "		\"pickup_date\": \"2019-08-01 07:22:57\","
                + "		\"dropoff_date\": \"2019-08-01 08:34:57\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 72,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 11.70,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 740,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 402,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-31 07:55:50\","
                + "		\"pickup_lat\": -1.29542330,"
                + "		\"pickup_lng\": 36.82190930,"
                + "		\"pickup_location\": \"Uhuru Highway Railway Bridge, Nairobi\","
                + "		\"dropoff_lat\": -1.32342070,"
                + "		\"dropoff_lng\": 36.84409670,"
                + "		\"dropoff_location\": \"Mombasa Road, Nairobi\","
                + "		\"pickup_date\": \"2019-07-31 07:56:07\","
                + "		\"dropoff_date\": \"2019-07-31 08:06:07\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 10,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 5.13,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 294,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 401,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-31 07:06:24\","
                + "		\"pickup_lat\": -1.27702660,"
                + "		\"pickup_lng\": 36.88596740,"
                + "		\"pickup_location\": \"Kangundo Rd, Nairobi\","
                + "		\"dropoff_lat\": -1.28785860,"
                + "		\"dropoff_lng\": 36.82724630,"
                + "		\"dropoff_location\": \"Aghro House, 08 Moi Ave, Nairobi\","
                + "		\"pickup_date\": \"2019-07-31 07:07:13\","
                + "		\"dropoff_date\": \"2019-07-31 07:52:13\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 45,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 12.72,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 662,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 366,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-23 18:52:06\","
                + "		\"pickup_lat\": -1.29375420,"
                + "		\"pickup_lng\": 36.82098220,"
                + "		\"pickup_location\": \"Shell Town, Nairobi\","
                + "		\"dropoff_lat\": -1.32353430,"
                + "		\"dropoff_lng\": 36.84354540,"
                + "		\"dropoff_location\": \"St James, Nairobi\","
                + "		\"pickup_date\": \"2019-07-23 18:52:32\","
                + "		\"dropoff_date\": \"2019-07-24 08:39:32\","
                + "		\"type\": \"Lady\","
                + "		\"driver_id\": 13,"
                + "		\"driver_name\": \"Alize\","
                + "		\"driver_rating\": 5,"
                + "		\"driver_pic\": \"https://demotaxiapp/p13.jpg\","
                + "		\"car_make\": \"Honda\","
                + "		\"car_model\": \"Civic\","
                + "		\"car_number\": \"KCR-100P\","
                + "		\"car_year\": 2012,"
                + "		\"car_pic\": \"https://demotaxiapp/c13.jpg\","
                + "		\"duration\": 827,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 19.63,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 3761,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 337,"
                + "		\"status\": \"CANCELED\","
                + "		\"request_date\": \"2019-07-23 12:53:53\","
                + "		\"pickup_lat\": -1.29282470,"
                + "		\"pickup_lng\": 36.81987770,"
                + "		\"pickup_location\": \"Ring Road Kileleshwa, Nairobi\","
                + "		\"dropoff_lat\": -1.32409440,"
                + "		\"dropoff_lng\": 36.84429720,"
                + "		\"dropoff_location\": \"Next Gen Mall, Nairobi\","
                + "		\"pickup_date\": \"2019-07-23 12:54:17\","
                + "		\"dropoff_date\": null,"
                + "		\"type\": \"Lady\","
                + "		\"driver_id\": 13,"
                + "		\"driver_name\": \"Alize\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p13.jpg\","
                + "		\"car_make\": \"Honda\","
                + "		\"car_model\": \"Civic\","
                + "		\"car_number\": \"KCR-100P\","
                + "		\"car_year\": 2012,"
                + "		\"car_pic\": \"https://demotaxiapp/c13.jpg\","
                + "		\"duration\": 0,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 0,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 0,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 336,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-23 11:39:16\","
                + "		\"pickup_lat\": -1.32389280,"
                + "		\"pickup_lng\": 36.84368430,"
                + "		\"pickup_location\": \"Eka Hotel/ Nextgen Mall, Nairobi\","
                + "		\"dropoff_lat\": -1.29282520,"
                + "		\"dropoff_lng\": 36.81985770,"
                + "		\"dropoff_location\": \"Ring road kileleshwa, Nairobi\","
                + "		\"pickup_date\": \"2019-07-23 11:45:42\","
                + "		\"dropoff_date\": \"2019-07-23 12:52:42\","
                + "		\"type\": \"Lady\","
                + "		\"driver_id\": 13,"
                + "		\"driver_name\": \"Alize\","
                + "		\"driver_rating\": 5,"
                + "		\"driver_pic\": \"https://demotaxiapp/p13.jpg\","
                + "		\"car_make\": \"Honda\","
                + "		\"car_model\": \"Civic\","
                + "		\"car_number\": \"KCR-100P\","
                + "		\"car_year\": 2012,"
                + "		\"car_pic\": \"https://demotaxiapp/c13.jpg\","
                + "		\"duration\": 67,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 10.55,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 539,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 331,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-22 19:49:05\","
                + "		\"pickup_lat\": -1.26935210,"
                + "		\"pickup_lng\": 36.80739350,"
                + "		\"pickup_location\": \"Unnamed Road, Nairobi\","
                + "		\"dropoff_lat\": -1.31618920,"
                + "		\"dropoff_lng\": 36.82723990,"
                + "		\"dropoff_location\": \"Rumi Road, Nairobi\","
                + "		\"pickup_date\": \"2019-07-22 19:53:31\","
                + "		\"dropoff_date\": \"2019-07-22 20:14:31\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 21,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 7.66,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 292,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 323,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-22 16:39:52\","
                + "		\"pickup_lat\": -1.32430790,"
                + "		\"pickup_lng\": 36.84353970,"
                + "		\"pickup_location\": \"Unnamed Road, Nairobi\","
                + "		\"dropoff_lat\": -1.27126430,"
                + "		\"dropoff_lng\": 36.80736210,"
                + "		\"dropoff_location\": \"Chiromo, Nairobi\","
                + "		\"pickup_date\": \"2019-07-22 16:40:40\","
                + "		\"dropoff_date\": \"2019-07-22 17:07:40\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 27,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 8.54,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 339,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 295,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-20 20:40:04\","
                + "		\"pickup_lat\": -1.26623870,"
                + "		\"pickup_lng\": 36.79656040,"
                + "		\"pickup_location\": \"79 David Osieli Rd, Nairobi\","
                + "		\"dropoff_lat\": -1.26548060,"
                + "		\"dropoff_lng\": 36.80199120,"
                + "		\"dropoff_location\": \"PwC Tower, Nairobi\","
                + "		\"pickup_date\": \"2019-07-20 20:40:29\","
                + "		\"dropoff_date\": \"2019-07-20 20:59:29\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 5,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 19,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 3.73,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 211,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 271,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-20 14:22:36\","
                + "		\"pickup_lat\": -1.27096310,"
                + "		\"pickup_lng\": 36.79625610,"
                + "		\"pickup_location\": \"9 Riverside, Nairobi\","
                + "		\"dropoff_lat\": -1.27096310,"
                + "		\"dropoff_lng\": 36.79625610,"
                + "		\"dropoff_location\": \"9 Riverside, Nairobi\","
                + "		\"pickup_date\": \"2019-07-20 14:25:14\","
                + "		\"dropoff_date\": \"2019-07-20 14:34:14\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 5,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 9,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 2.08,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 200,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 219,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-15 07:17:16\","
                + "		\"pickup_lat\": -1.28631570,"
                + "		\"pickup_lng\": 36.82666290,"
                + "		\"pickup_location\": \"Tom Mboya Junction, Ronald Ngala St, Nairobi\","
                + "		\"dropoff_lat\": -1.32233340,"
                + "		\"dropoff_lng\": 36.84605180,"
                + "		\"dropoff_location\": \"Unnamed Road, Nairobi\","
                + "		\"pickup_date\": \"2019-07-15 07:17:27\","
                + "		\"dropoff_date\": \"2019-07-15 08:19:27\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 62,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 8.40,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 445,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 218,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-12 21:07:05\","
                + "		\"pickup_lat\": -1.29402160,"
                + "		\"pickup_lng\": 36.82132970,"
                + "		\"pickup_location\": \"Shell Haile selassie junction, Nairobi\","
                + "		\"dropoff_lat\": -1.32357790,"
                + "		\"dropoff_lng\": 36.84335280,"
                + "		\"dropoff_location\": \"Mombasa Road, Wambco Court, Nairobi\","
                + "		\"pickup_date\": \"2019-07-12 21:07:17\","
                + "		\"dropoff_date\": \"2019-07-15 12:09:17\","
                + "		\"type\": \"Lady\","
                + "		\"driver_id\": 13,"
                + "		\"driver_name\": \"Alize\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p13.jpg\","
                + "		\"car_make\": \"Honda\","
                + "		\"car_model\": \"Civic\","
                + "		\"car_number\": \"KCR-100P\","
                + "		\"car_year\": 2012,"
                + "		\"car_pic\": \"https://demotaxiapp/c13.jpg\","
                + "		\"duration\": 3782,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 25.19,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 15692,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 204,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-12 07:40:58\","
                + "		\"pickup_lat\": -1.28428410,"
                + "		\"pickup_lng\": 36.82603110,"
                + "		\"pickup_location\": \"City Clock, Accra Rd, Nairobi\","
                + "		\"dropoff_lat\": -1.32345430,"
                + "		\"dropoff_lng\": 36.84328470,"
                + "		\"dropoff_location\": \"Mombasa Road, Wambco Court, Nairobi\","
                + "		\"pickup_date\": \"2019-07-12 07:41:12\","
                + "		\"dropoff_date\": \"2019-07-12 08:07:12\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 26,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 6.59,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 293,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 203,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-12 06:46:17\","
                + "		\"pickup_lat\": -1.26835320,"
                + "		\"pickup_lng\": 36.90572300,"
                + "		\"pickup_location\": \"Phase 4/Car Wash, Nairobi\","
                + "		\"dropoff_lat\": -1.28358890,"
                + "		\"dropoff_lng\": 36.82519560,"
                + "		\"dropoff_location\": \"72291 Tom Mboya St, Nairobi\","
                + "		\"pickup_date\": \"2019-07-12 06:46:38\","
                + "		\"dropoff_date\": \"2019-07-12 07:37:38\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 51,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 9.02,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 429,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 202,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-11 18:22:49\","
                + "		\"pickup_lat\": -1.28631840,"
                + "		\"pickup_lng\": 36.82661100,"
                + "		\"pickup_location\": \"Magomano, Tom Mboya St, Nairobi\","
                + "		\"dropoff_lat\": -1.26468870,"
                + "		\"dropoff_lng\": 36.91162970,"
                + "		\"dropoff_location\": \"Unnamed Road, Nairobi\","
                + "		\"pickup_date\": \"2019-07-11 18:26:20\","
                + "		\"dropoff_date\": \"2019-07-11 19:58:20\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 92,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 19.33,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 810,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 201,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-11 17:11:13\","
                + "		\"pickup_lat\": -1.29010940,"
                + "		\"pickup_lng\": 36.78700300,"
                + "		\"pickup_location\": \"Spanish Villas/Lenana, Nairobi\","
                + "		\"dropoff_lat\": -1.28373210,"
                + "		\"dropoff_lng\": 36.82155310,"
                + "		\"dropoff_location\": \"Banda St, Nairobi\","
                + "		\"pickup_date\": \"2019-07-11 17:11:27\","
                + "		\"dropoff_date\": \"2019-07-11 17:36:27\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 25,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 5.27,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 257,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 199,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-11 14:02:10\","
                + "		\"pickup_lat\": -1.28116490,"
                + "		\"pickup_lng\": 36.81743170,"
                + "		\"pickup_location\": \"College House, University Way, Nairobi\","
                + "		\"dropoff_lat\": -1.28988000,"
                + "		\"dropoff_lng\": 36.78688280,"
                + "		\"dropoff_location\": \"Spanish Villas/Lenana, Nairobi\","
                + "		\"pickup_date\": \"2019-07-11 14:02:24\","
                + "		\"dropoff_date\": \"2019-07-11 14:35:24\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 33,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 5.48,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 286,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 197,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-11 13:06:13\","
                + "		\"pickup_lat\": -1.32363560,"
                + "		\"pickup_lng\": 36.84368730,"
                + "		\"pickup_location\": \"Eka Hotel/ Nextgen Mall, Nairobi\","
                + "		\"dropoff_lat\": -1.28570120,"
                + "		\"dropoff_lng\": 36.81851140,"
                + "		\"dropoff_location\": \"GPO, Nairobi\","
                + "		\"pickup_date\": \"2019-07-11 13:06:36\","
                + "		\"dropoff_date\": \"2019-07-11 13:27:36\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 21,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 6.13,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 267,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 169,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-08 07:45:26\","
                + "		\"pickup_lat\": -1.31818830,"
                + "		\"pickup_lng\": 36.83575670,"
                + "		\"pickup_location\": \"A104, Nairobi\","
                + "		\"dropoff_lat\": -1.23577880,"
                + "		\"dropoff_lng\": 36.81144900,"
                + "		\"dropoff_location\": \"ICRAF Rd, Nairobi\","
                + "		\"pickup_date\": \"2019-07-08 07:45:59\","
                + "		\"dropoff_date\": \"2019-07-08 08:46:59\","
                + "		\"type\": \"HavaXL\","
                + "		\"driver_id\": 11,"
                + "		\"driver_name\": \"George\","
                + "		\"driver_rating\": 5,"
                + "		\"driver_pic\": \"https://demotaxiapp/p11.jpg\","
                + "		\"car_make\": \"Toyota\","
                + "		\"car_model\": \"Rav4\","
                + "		\"car_number\": \"KBG-871X\","
                + "		\"car_year\": 2009,"
                + "		\"car_pic\": \"https://demotaxiapp/c11.jpg\","
                + "		\"duration\": 61,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 15.93,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 591,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 145,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-05 16:16:43\","
                + "		\"pickup_lat\": -1.32374340,"
                + "		\"pickup_lng\": 36.84442400,"
                + "		\"pickup_location\": \"A104, Nairobi\","
                + "		\"dropoff_lat\": -1.26162660,"
                + "		\"dropoff_lng\": 36.79725300,"
                + "		\"dropoff_location\": \"St. Marks / Lions Place, Nairobi\","
                + "		\"pickup_date\": \"2019-07-05 16:17:20\","
                + "		\"dropoff_date\": \"2019-07-05 16:46:20\","
                + "		\"type\": \"HavaXL\","
                + "		\"driver_id\": 11,"
                + "		\"driver_name\": \"George\","
                + "		\"driver_rating\": 5,"
                + "		\"driver_pic\": \"https://demotaxiapp/p11.jpg\","
                + "		\"car_make\": \"Toyota\","
                + "		\"car_model\": \"Rav4\","
                + "		\"car_number\": \"KBG-871X\","
                + "		\"car_year\": 2009,"
                + "		\"car_pic\": \"https://demotaxiapp/c11.jpg\","
                + "		\"duration\": 29,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 9.17,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 173,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 117,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-04 20:51:41\","
                + "		\"pickup_lat\": -1.32424740,"
                + "		\"pickup_lng\": 36.84357360,"
                + "		\"pickup_location\": \"Unnamed Road, Nairobi\","
                + "		\"dropoff_lat\": -1.33043350,"
                + "		\"dropoff_lng\": 36.92464390,"
                + "		\"dropoff_location\": \"Unnamed Road, Nairobi\","
                + "		\"pickup_date\": \"2019-07-04 21:07:10\","
                + "		\"dropoff_date\": \"2019-07-04 21:40:10\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 5,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 33,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 17.12,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 271,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 116,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-04 17:10:03\","
                + "		\"pickup_lat\": -1.28217320,"
                + "		\"pickup_lng\": 36.82063240,"
                + "		\"pickup_location\": \"10, Nairobi\","
                + "		\"dropoff_lat\": -1.32369600,"
                + "		\"dropoff_lng\": 36.84386150,"
                + "		\"dropoff_location\": \"Eka Hotel/ Nextgen Mall, Nairobi\","
                + "		\"pickup_date\": \"2019-07-04 17:10:24\","
                + "		\"dropoff_date\": \"2019-07-04 18:14:24\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 5,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 64,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 13.77,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 237,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 89,"
                + "		\"status\": \"CANCELED\","
                + "		\"request_date\": \"2019-07-04 13:41:39\","
                + "		\"pickup_lat\": -1.28119150,"
                + "		\"pickup_lng\": 36.81729370,"
                + "		\"pickup_location\": \"11 Koinange St, Nairobi\","
                + "		\"dropoff_lat\": -1.26184760,"
                + "		\"dropoff_lng\": 36.80412170,"
                + "		\"dropoff_location\": \"9 West, Mkungu Cl, Nairobi\","
                + "		\"pickup_date\": \"2019-07-04 13:42:05\","
                + "		\"dropoff_date\": null,"
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 0,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 0,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 0,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 0,"
                + "		\"cost_unit\": \"KES\""
                + "	}, {"
                + "		\"id\": 78,"
                + "		\"status\": \"COMPLETED\","
                + "		\"request_date\": \"2019-07-04 11:21:49\","
                + "		\"pickup_lat\": -1.30624440,"
                + "		\"pickup_lng\": 36.82700470,"
                + "		\"pickup_location\": \"Peugot, Nairobi\","
                + "		\"dropoff_lat\": -1.28387390,"
                + "		\"dropoff_lng\": 36.81903250,"
                + "		\"dropoff_location\": \"City Market Building, Koinange Street, Nairobi\","
                + "		\"pickup_date\": \"2019-07-04 11:31:14\","
                + "		\"dropoff_date\": \"2019-07-04 11:45:14\","
                + "		\"type\": \"Basic\","
                + "		\"driver_id\": 9,"
                + "		\"driver_name\": \"Richard\","
                + "		\"driver_rating\": 5,"
                + "		\"driver_pic\": \"https://demotaxiapp/p9.jpg\","
                + "		\"car_make\": \"Nissan\","
                + "		\"car_model\": \"March\","
                + "		\"car_number\": \"KCQ-6711\","
                + "		\"car_year\": 2015,"
                + "		\"car_pic\": \"https://demotaxiapp/c9.jpg\","
                + "		\"duration\": 14,"
                + "		\"duration_unit\": \"min\","
                + "		\"distance\": 3.13,"
                + "		\"distance_unit\": \"km\","
                + "		\"cost\": 225,"
                + "		\"cost_unit\": \"KES\""
                + "	}]"
                + "}";
        return sourcestr;
    }
}
